name: ExtDN Actions
on: [push]
jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-unit-tests/7.3@master
        env:
          MODULE_NAME: Sansec_Shield
          COMPOSER_NAME: sansec/magento2-module-shield
