name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: gd, mcrypt, curl, intl, xsl, mbstring, openssl, zip, soap, bcmath
      - uses: actions/checkout@v3
      - run: composer global config http-basic.repo.magento.com ${{ secrets.MAGENTO_USERNAME }} ${{ secrets.MAGENTO_PASSWORD }}
      - run: composer install
      - run: ./vendor/bin/phpunit Test
